name: Auto Deployment

on:
  push:
    branches:
      - master # 只在master上push触发部署
    
jobs:
  deploy:
    runs-on: ubuntu-latest # 使用ubuntu系统镜像运行自动化脚本

    steps: # 自动化步骤
      #下载代码仓库
      - uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      # 安装依赖
      - name: pnpm install 
        run: pnpm install 
    
      #打包项目
      - name: Build
        run: pnpm build

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
        ssh-private-key: ${{ secrets.LYUS_RSA }}

      - name: pull files
        run: |
         ssh root@${{ secrets.LYUS_IP }} "
          git pull
        "
      - name: install dependences
        run: |
         ssh root@${{ secrets.LYUS_IP }} "
          pnpm i
        "
      - name: pnpm build
        run: |
         ssh root@${{ secrets.LYUS_IP }} "
          pnpm build
        "

